POST https://greet-api.onrender.com/api/greet
content-type: application/json

{
	"language" : "xhosa",
	"greeting" : "Molo"
}

###

POST https://greet-api.onrender.com/api/greet
content-type: application/json

{
	"language" : "zulu",
	"greeting" : "Sawubona"
}
###

POST https://greet-api.onrender.com/api/greet
content-type: application/json

{
	"language" : "English",
	"greeting" : "Hello"
}
###

POST https://greet-api.onrender.com/api/greet
content-type: application/json

{
	"language" : "Venda",
	"greeting" : "Nda"
}

